services:

  database:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: traccar
      POSTGRES_USER: traccar
      POSTGRES_PASSWORD: traccar
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U traccar -d traccar"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - db_data:/var/lib/postgresql

  traccar:
    image: traccar/traccar:latest
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    environment:
      CONFIG_USE_ENVIRONMENT_VARIABLES: "true"
      DATABASE_DRIVER: org.postgresql.Driver
      DATABASE_URL: jdbc:postgresql://database:5432/traccar
      DATABASE_USER: traccar
      DATABASE_PASSWORD: traccar
      DATABASE_REGISTERUNKNOWN: "true"
    ports:
      - "8082:8082"
      - "5055:5055"
    volumes:
      - ./logs:/opt/traccar/logs
      - ./traccar.xml:/opt/traccar/conf/traccar.xml:ro

volumes:
  db_data: